#!/bin/sh
erl -config ~/GIT/prisms/resource_discovery/rel/files/app -pa ebin -pa ../erlang-stomp-client/ebin -pa deps/ossp_uuid/ebin -pa deps/handyman/ebin #\
    #-eval "{MainPid, Pid} = rd_host_resource:stboth()."

