#!/bin/sh
#erl -config ~/GIT/prisms/resource_discovery/rel/files/app -pa ebin -pa ../erlang-stomp-client/ebin -pa deps/ossp_uuid/ebin -pa deps/handyman/ebin -eval "{ok, Pid} = rd_host_server:start_link()." 
#erl -config ~/GIT/prisms/resource_discovery/rel/files/app -pa ebin -pa deps/stomp_client/ebin -pa deps/ossp_uuid/ebin -pa deps/handyman/ebin -eval "{ok, Pid} = rd_host_server:start_link()." 
erl -config ~/GIT/prisms/resource_discovery/rel/files/app -pa ebin -pa deps/stomp_client/ebin -pa deps/ossp_uuid/ebin -pa deps/handyman/ebin -eval "rd_app:start()." 

